package com.serverless.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "Equipment")
public class Equipment {

    String EquipmentNumber;
    String Status;

    @DynamoDBAutoGeneratedKey
    @DynamoDBHashKey(attributeName = "EquipmentNumber")
    public String getEquipmentNumber() {
        return EquipmentNumber;
    }

    public void setEquipmentNumber(String equipmentNumber) {
        this.EquipmentNumber = equipmentNumber;
    }

    public String getStatus() {
        return Status;
    }

    public void setStatus(String status) {
        this.Status = status;
    }

}
