package com.serverless.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

import java.io.Serializable;

@DynamoDBTable(tableName = "Equipment-dev")
public class Equipment implements Serializable {

    private static final long serialVersionUID = 2532762991005262032L;

    String UUID;
    String EquipmentNumber;
    String Address;
    String ContractStartDate;
    String ContractEndDate;
    String Status;

    @DynamoDBAttribute(attributeName="UUID")
    @DynamoDBAutoGeneratedKey
    public String getUUID() { return UUID; }
    public void setUUID(String UUID) { this.UUID = UUID; }

    @DynamoDBHashKey(attributeName = "EquipmentNumber")
    public String getEquipmentNumber() {
        return EquipmentNumber;
    }
    public void setEquipmentNumber(String equipmentNumber) {
        this.EquipmentNumber = equipmentNumber;
    }

    @DynamoDBAttribute(attributeName="Address")
    public void setAddress(String address) { Address = address; }
    public String getAddress() { return Address; }

    @DynamoDBAttribute(attributeName="contractStartDate")
    public void setContractStartDate(String contractStartDate) { ContractStartDate = contractStartDate; }
    public String getContractStartDate() { return ContractStartDate; }

    @DynamoDBAttribute(attributeName="ContractEndDate")
    public void setContractEndDate(String contractEndDate) { ContractEndDate = contractEndDate; }
    public String getContractEndDate() { return ContractEndDate; }

    @DynamoDBAttribute(attributeName="Status")
    public String getStatus() { return Status; }
    public void setStatus(String status) { this.Status = status; }


}
